//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academy
    {
        public  Academy ToPoco()
        {
            return new Academy()
            {
              ID = this.ID,
              Description = this.Description,
              Name = this.Name,
              Population = this.Population,
              President = this.President,
              Phone = this.Phone,
              SiteUrl = this.SiteUrl,
              IconUrl = this.IconUrl,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              SubTime = this.SubTime,
              VicePresidentA = this.VicePresidentA,
              VicePresidentB = this.VicePresidentB,
              VicePresidentC = this.VicePresidentC,
              VicePresidentD = this.VicePresidentD,
              User = this.User,
              ClassInfo = this.ClassInfo,
              Course = this.Course,
            };
    
        }
    
    
    }
}
