//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academy
    {
        public Academy()
        {
            this.Population = 0;
            this.IsDeleted = 0;
            this.User = new HashSet<User>();
            this.ClassInfo = new HashSet<ClassInfo>();
            this.Course = new HashSet<Course>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<int> Population { get; set; }
        public string President { get; set; }
        public string Phone { get; set; }
        public string SiteUrl { get; set; }
        public string IconUrl { get; set; }
        public string Remark { get; set; }
        public Nullable<short> IsDeleted { get; set; }
        public string SubTime { get; set; }
        public string VicePresidentA { get; set; }
        public string VicePresidentB { get; set; }
        public string VicePresidentC { get; set; }
        public string VicePresidentD { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<ClassInfo> ClassInfo { get; set; }
        public virtual ICollection<Course> Course { get; set; }
    }
}
