//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public  Article ToPoco()
        {
            return new Article()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              Title = this.Title,
              Content = this.Content,
              EndTime = this.EndTime,
              PublishTime = this.PublishTime,
              ArticleType = this.ArticleType,
              LikePoint = this.LikePoint,
              RecommendPoint = this.RecommendPoint,
              DislikePoint = this.DislikePoint,
              ReadTimes = this.ReadTimes,
              Tips = this.Tips,
              IsItemUseToTitle = this.IsItemUseToTitle,
              IsItemUseToContent = this.IsItemUseToContent,
              PublisherID = this.PublisherID,
              Publisher = this.Publisher,
              Attachment = this.Attachment,
              CollectUser = this.CollectUser,
              Comment = this.Comment,
            };
    
        }
    
    
    }
}
