//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigQuestion
    {
        public  BigQuestion ToPoco()
        {
            return new BigQuestion()
            {
              ID = this.ID,
              Title = this.Title,
              Remark = this.Remark,
              SubTime = this.SubTime,
              Score = this.Score,
              IsDeleted = this.IsDeleted,
              TestPaperID = this.TestPaperID,
              TestPaper = this.TestPaper,
            };
    
        }
    
    
    }
}
