//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceQuestion
    {
        public  ChoiceQuestion ToPoco()
        {
            return new ChoiceQuestion()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              Content = this.Content,
              SelectA = this.SelectA,
              SelectB = this.SelectB,
              SelectC = this.SelectC,
              SelectD = this.SelectD,
              SelectE = this.SelectE,
              SelectF = this.SelectF,
              Answers = this.Answers,
              IsMultiSelect = this.IsMultiSelect,
              IsPublic = this.IsPublic,
              Difficulty = this.Difficulty,
              PublisherID = this.PublisherID,
              CourseID = this.CourseID,
              Publisher = this.Publisher,
              Course = this.Course,
            };
    
        }
    
    
    }
}
