//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassInfo
    {
        public  ClassInfo ToPoco()
        {
            return new ClassInfo()
            {
              ID = this.ID,
              ClassName = this.ClassName,
              Population = this.Population,
              SiteUrl = this.SiteUrl,
              ClassIcon = this.ClassIcon,
              SubTime = this.SubTime,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              AcademyID = this.AcademyID,
              MonitorID = this.MonitorID,
              TeacherID = this.TeacherID,
              Student = this.Student,
              Academy = this.Academy,
            };
    
        }
    
    
    }
}
