//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassInfo
    {
        public ClassInfo()
        {
            this.Population = 0;
            this.Remark = "请填写您的说明信息";
            this.IsDeleted = 0;
            this.Student = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string ClassName { get; set; }
        public Nullable<short> Population { get; set; }
        public string SiteUrl { get; set; }
        public string ClassIcon { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Remark { get; set; }
        public short IsDeleted { get; set; }
        public int AcademyID { get; set; }
        public Nullable<int> MonitorID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual ICollection<User> Student { get; set; }
        public virtual Academy Academy { get; set; }
    }
}
