//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.CourseName = "请填写您的说明信息";
            this.Description = "请填写您的说明信息";
            this.TestPaper = new HashSet<TestPaper>();
            this.ChoiceQuestion = new HashSet<ChoiceQuestion>();
            this.FillingQuestion = new HashSet<FillingQuestion>();
            this.ShortQuestion = new HashSet<ShortQuestion>();
            this.TrueFalseQuestion = new HashSet<TrueFalseQuestion>();
            this.Academy = new HashSet<Academy>();
        }
    
        public int ID { get; set; }
        public short IsDeleted { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Remark { get; set; }
        public string CourseName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TestPaper> TestPaper { get; set; }
        public virtual ICollection<ChoiceQuestion> ChoiceQuestion { get; set; }
        public virtual ICollection<FillingQuestion> FillingQuestion { get; set; }
        public virtual ICollection<ShortQuestion> ShortQuestion { get; set; }
        public virtual ICollection<TrueFalseQuestion> TrueFalseQuestion { get; set; }
        public virtual ICollection<Academy> Academy { get; set; }
    }
}
