//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Population = 0;
            this.IsDeleted = 0;
            this.ParentId = 0;
            this.IsLeaf = true;
            this.Level = 0;
            this.User = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Population { get; set; }
        public string SubTime { get; set; }
        public string Boss { get; set; }
        public string Phone { get; set; }
        public string SiteUrl { get; set; }
        public string IconUrl { get; set; }
        public string Remark { get; set; }
        public short IsDeleted { get; set; }
        public string Number { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
        public Nullable<short> Level { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
