//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public  Department ToPoco()
        {
            return new Department()
            {
              ID = this.ID,
              Name = this.Name,
              Population = this.Population,
              SubTime = this.SubTime,
              Boss = this.Boss,
              Phone = this.Phone,
              SiteUrl = this.SiteUrl,
              IconUrl = this.IconUrl,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              Number = this.Number,
              ParentId = this.ParentId,
              IsLeaf = this.IsLeaf,
              Level = this.Level,
              User = this.User,
            };
    
        }
    
    
    }
}
