//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.FileSize = 0;
            this.DownloadTimes = 0;
        }
    
        public int ID { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> DownloadTimes { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ArticleID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
