//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public  File ToPoco()
        {
            return new File()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              FileName = this.FileName,
              FileType = this.FileType,
              FileSize = this.FileSize,
              FileUrl = this.FileUrl,
              DownloadTimes = this.DownloadTimes,
              UserID = this.UserID,
              ArticleID = this.ArticleID,
              Article = this.Article,
              User = this.User,
            };
    
        }
    
    
    }
}
