//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillingQuestion
    {
        public FillingQuestion()
        {
            this.IsDeleted = 0;
            this.Remark = "请填写说明信息";
            this.Content = "试题内容";
            this.Answers = "答案";
            this.IsPublic = true;
            this.IsMultiFilling = false;
            this.Difficulty = 3;
        }
    
        public int ID { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Content { get; set; }
        public string Answers { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<bool> IsMultiFilling { get; set; }
        public Nullable<short> Difficulty { get; set; }
        public int CourseID { get; set; }
        public int PublisherID { get; set; }
    
        public virtual User Publisher { get; set; }
        public virtual Course Course { get; set; }
    }
}
