//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public Friend()
        {
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
        }
    
        public int ID { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public System.DateTime SubTime { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
