//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public  Item ToPoco()
        {
            return new Item()
            {
              Id = this.Id,
              Name = this.Name,
              Effect = this.Effect,
              Target = this.Target,
              Price = this.Price,
              EffectDays = this.EffectDays,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              ItemEffectType = this.ItemEffectType,
              ImageUrl = this.ImageUrl,
              EntTIme = this.EntTIme,
              UserItem = this.UserItem,
            };
    
        }
    
    
    }
}
