//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Price = 0;
            this.EffectDays = 0;
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.UserItem = new HashSet<UserItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Effect { get; set; }
        public Nullable<ItemTargetType> Target { get; set; }
        public int Price { get; set; }
        public int EffectDays { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public ItemEffectType ItemEffectType { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> EntTIme { get; set; }
    
        public virtual ICollection<UserItem> UserItem { get; set; }
    }
}
