//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    
    public enum ItemTargetType : short
    {
        ToUserSelf = 0,
        ToOtherUser = 1,
        ToUserSelfAndOtherUser = 2,
        ToUserSelfOrOtherUser = 3,
        ToArticle = 4,
        ToArticleTitle = 5,
        ToArticleComment = 6,
        ToItem = 7,
        ToFile = 8
    }
}
