//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public  Permission ToPoco()
        {
            return new Permission()
            {
              ID = this.ID,
              Url = this.Url,
              HttpMethod = this.HttpMethod,
              Action = this.Action,
              Remark = this.Remark,
              Controoller = this.Controoller,
              Area = this.Area,
              SubTime = this.SubTime,
              IsDeleted = this.IsDeleted,
              Role = this.Role,
              SpecialPermission = this.SpecialPermission,
            };
    
        }
    
    
    }
}
