//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.HttpMethod = "get";
            this.IsDeleted = 0;
            this.Role = new HashSet<Role>();
            this.SpecialPermission = new HashSet<SpecialPermission>();
        }
    
        public int ID { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string Action { get; set; }
        public string Remark { get; set; }
        public string Controoller { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public short IsDeleted { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<SpecialPermission> SpecialPermission { get; set; }
    }
}
