//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialPermission
    {
        public  SpecialPermission ToPoco()
        {
            return new SpecialPermission()
            {
              ID = this.ID,
              SubTime = this.SubTime,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              UserID = this.UserID,
              PermissionID = this.PermissionID,
              IsPass = this.IsPass,
              User = this.User,
              Permission = this.Permission,
            };
    
        }
    
    
    }
}
