//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialPermission
    {
        public SpecialPermission()
        {
            this.Remark = "请填写您的说明信息";
            this.IsDeleted = 0;
            this.IsPass = true;
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Remark { get; set; }
        public short IsDeleted { get; set; }
        public int UserID { get; set; }
        public int PermissionID { get; set; }
        public bool IsPass { get; set; }
    
        public virtual User User { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
