//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPaper
    {
        public  StudentPaper ToPoco()
        {
            return new StudentPaper()
            {
              ID = this.ID,
              PaperScore = this.PaperScore,
              SubmitTime = this.SubmitTime,
              StartTime = this.StartTime,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              TeacherWords = this.TeacherWords,
              TestPaperID = this.TestPaperID,
              UserID = this.UserID,
              User = this.User,
              TestPaper = this.TestPaper,
            };
    
        }
    
    
    }
}
