//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPaper
    {
        public StudentPaper()
        {
            this.PaperScore = 100;
            this.Remark = "请填写您的说明信息";
            this.IsDeleted = 0;
            this.TeacherWords = "请在这里填写您的评语";
        }
    
        public int ID { get; set; }
        public short PaperScore { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Remark { get; set; }
        public short IsDeleted { get; set; }
        public string TeacherWords { get; set; }
        public int TestPaperID { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual TestPaper TestPaper { get; set; }
    }
}
