//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public  TestPaper ToPoco()
        {
            return new TestPaper()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              SubTime = this.SubTime,
              Remark = this.Remark,
              PaperName = this.PaperName,
              PaperDescription = this.PaperDescription,
              PaperDate = this.PaperDate,
              StartTime = this.StartTime,
              EndTime = this.EndTime,
              PaperScore = this.PaperScore,
              PaperType = this.PaperType,
              PublisherID = this.PublisherID,
              CourseID = this.CourseID,
              CategoryID = this.CategoryID,
              Knowledge = this.Knowledge,
              TestMinutes = this.TestMinutes,
              VerifyBy = this.VerifyBy,
              CheckBy = this.CheckBy,
              StudentPaper = this.StudentPaper,
              BigQuestion = this.BigQuestion,
              Publisher = this.Publisher,
              Course = this.Course,
            };
    
        }
    
    
    }
}
