//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrueFalseQuestion
    {
        public  TrueFalseQuestion ToPoco()
        {
            return new TrueFalseQuestion()
            {
              ID = this.ID,
              Difficulty = this.Difficulty,
              IsPublic = this.IsPublic,
              Answers = this.Answers,
              Content = this.Content,
              SubTime = this.SubTime,
              Remark = this.Remark,
              IsDeleted = this.IsDeleted,
              CourseID = this.CourseID,
              PublisherID = this.PublisherID,
              Publisher = this.Publisher,
              Course = this.Course,
            };
    
        }
    
    
    }
}
