//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public  UserInfo ToPoco()
        {
            return new UserInfo()
            {
              ID = this.ID,
              Gender = this.Gender,
              Birthday = this.Birthday,
              Interest = this.Interest,
              Height = this.Height,
              Weight = this.Weight,
              BlogUrl = this.BlogUrl,
              MicroBlogUrl = this.MicroBlogUrl,
              WeChatAccount = this.WeChatAccount,
              LivePlace = this.LivePlace,
              GovFace = this.GovFace,
              IdNumber = this.IdNumber,
              TelNumber = this.TelNumber,
              QqNumber = this.QqNumber,
              IsDeleted = this.IsDeleted,
              SubTime = this.SubTime,
              Remark = this.Remark,
              Address = this.Address,
              HeadImageUrl = this.HeadImageUrl,
              User = this.User,
            };
    
        }
    
    
    }
}
