//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItem
    {
        public UserItem()
        {
            this.Count = 0;
            this.UsedCount = 0;
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
        }
    
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> StartUseTime { get; set; }
        public int UsedCount { get; set; }
        public Nullable<System.DateTime> EndUseTime { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public int UserID { get; set; }
        public int ItemID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
    }
}
