//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Gender = "未知";
            this.Weight = 50;
            this.TelNumber = "请填写您的说明信息";
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.HeadImageUrl = "/content/images/head/default.jpg";
        }
    
        public int ID { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Interest { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string BlogUrl { get; set; }
        public string MicroBlogUrl { get; set; }
        public string WeChatAccount { get; set; }
        public string LivePlace { get; set; }
        public string GovFace { get; set; }
        public string IdNumber { get; set; }
        public string TelNumber { get; set; }
        public Nullable<float> QqNumber { get; set; }
        public short IsDeleted { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string Remark { get; set; }
        public string Address { get; set; }
        public string HeadImageUrl { get; set; }
    
        public virtual User User { get; set; }
    }
}
