//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.NickName = "NewUser";
            this.UserPwd = "123456";
            this.Experiences = 0;
            this.Golds = 0;
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.IsLocked = 0;
            this.IsItemUsedToNickName = false;
            this.StudentPaper = new HashSet<StudentPaper>();
            this.Department = new HashSet<Department>();
            this.Role = new HashSet<Role>();
            this.VerifyPaper = new HashSet<TestPaper>();
            this.CheckPaper = new HashSet<TestPaper>();
            this.FillingQuestion = new HashSet<FillingQuestion>();
            this.ShortQuestion = new HashSet<ShortQuestion>();
            this.TrueFalseQuestion = new HashSet<TrueFalseQuestion>();
            this.SpecialPermission = new HashSet<SpecialPermission>();
            this.Article = new HashSet<Article>();
            this.File = new HashSet<File>();
            this.FavoriteArticle = new HashSet<Article>();
            this.UserItem = new HashSet<UserItem>();
            this.TestPaper = new HashSet<TestPaper>();
            this.ChoiceQuestion = new HashSet<ChoiceQuestion>();
            this.Answer = new HashSet<Answer>();
            this.Voted = new HashSet<Voted>();
            this.Vote = new HashSet<Vote>();
        }
    
        public int ID { get; set; }
        public string UserNumber { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string UserPwd { get; set; }
        public int Experiences { get; set; }
        public int Golds { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string Email { get; set; }
        public string SafeQuestion { get; set; }
        public string SafeAnswer { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public short IsLocked { get; set; }
        public int ClassInfoID { get; set; }
        public Nullable<bool> IsItemUsedToNickName { get; set; }
        public int AcademyID { get; set; }
        public int VoteID { get; set; }
    
        public virtual ICollection<StudentPaper> StudentPaper { get; set; }
        public virtual ClassInfo ClassInfo { get; set; }
        public virtual Academy Academy { get; set; }
        public virtual ICollection<Department> Department { get; set; }
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<TestPaper> VerifyPaper { get; set; }
        public virtual ICollection<TestPaper> CheckPaper { get; set; }
        public virtual ICollection<FillingQuestion> FillingQuestion { get; set; }
        public virtual ICollection<ShortQuestion> ShortQuestion { get; set; }
        public virtual ICollection<TrueFalseQuestion> TrueFalseQuestion { get; set; }
        public virtual ICollection<SpecialPermission> SpecialPermission { get; set; }
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<File> File { get; set; }
        public virtual ICollection<Article> FavoriteArticle { get; set; }
        public virtual ICollection<UserItem> UserItem { get; set; }
        public virtual ICollection<TestPaper> TestPaper { get; set; }
        public virtual ICollection<ChoiceQuestion> ChoiceQuestion { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual ICollection<Voted> Voted { get; set; }
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
