//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItem
    {
        public  UserItem ToPoco()
        {
            return new UserItem()
            {
              Id = this.Id,
              Count = this.Count,
              StartUseTime = this.StartUseTime,
              UsedCount = this.UsedCount,
              EndUseTime = this.EndUseTime,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              UserID = this.UserID,
              ItemID = this.ItemID,
              User = this.User,
              Item = this.Item,
            };
    
        }
    
    
    }
}
