//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public  Vote ToPoco()
        {
            return new Vote()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              ClassName = this.ClassName,
              VoteTitle = this.VoteTitle,
              VoteContent = this.VoteContent,
              Option1 = this.Option1,
              Option2 = this.Option2,
              Option3 = this.Option3,
              Option4 = this.Option4,
              Option5 = this.Option5,
              Option6 = this.Option6,
              Option7 = this.Option7,
              Option8 = this.Option8,
              Option9 = this.Option9,
              Option10 = this.Option10,
              ParentId = this.ParentId,
              MoreInfo = this.MoreInfo,
              IsEnded = this.IsEnded,
              IsMutilSelect = this.IsMutilSelect,
              MutilSelectCount = this.MutilSelectCount,
              StartTime = this.StartTime,
              EndTime = this.EndTime,
              VoteImageUrl = this.VoteImageUrl,
              VoteClassID = this.VoteClassID,
              PublisherID = this.PublisherID,
              Voted = this.Voted,
              VoteClass = this.VoteClass,
              Publisher = this.Publisher,
            };
    
        }
    
    
    }
}
