//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public Vote()
        {
            this.IsDeleted = 0;
            this.Remark = "请填写您的说明信息";
            this.ClassName = "无";
            this.VoteTitle = "投票标题";
            this.VoteContent = "投票内容";
            this.ParentId = 0;
            this.MoreInfo = "无说明信息";
            this.IsEnded = false;
            this.IsMutilSelect = false;
            this.MutilSelectCount = 1;
            this.Voted = new HashSet<Voted>();
        }
    
        public int ID { get; set; }
        public short IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string ClassName { get; set; }
        public string VoteTitle { get; set; }
        public string VoteContent { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        public string Option6 { get; set; }
        public string Option7 { get; set; }
        public string Option8 { get; set; }
        public string Option9 { get; set; }
        public string Option10 { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MoreInfo { get; set; }
        public Nullable<bool> IsEnded { get; set; }
        public bool IsMutilSelect { get; set; }
        public short MutilSelectCount { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string VoteImageUrl { get; set; }
        public Nullable<int> VoteClassID { get; set; }
        public int PublisherID { get; set; }
    
        public virtual ICollection<Voted> Voted { get; set; }
        public virtual VoteClass VoteClass { get; set; }
        public virtual User Publisher { get; set; }
    }
}
