//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voted
    {
        public  Voted ToPoco()
        {
            return new Voted()
            {
              ID = this.ID,
              IsDeleted = this.IsDeleted,
              Remark = this.Remark,
              SubTime = this.SubTime,
              Reason = this.Reason,
              SelectOptions = this.SelectOptions,
              PostTime = this.PostTime,
              VoteID = this.VoteID,
              UserID = this.UserID,
              Vote = this.Vote,
              User = this.User,
            };
    
        }
    
    
    }
}
